#!/bin/bash

set -e

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

[ -d $SNAP_COMMON/config ] && [ -e $SNAP_COMMON/config/flask_secrets ] && export FLASK_SECRETS=$SNAP_COMMON/config/flask_secrets

exec "$SNAP/bin/gunicorn" --chdir "$SNAP/flask-app" --config "$SNAP/flask-app/server.cfg" --bind 0.0.0.0:8000 wsgi:app "$@"