name: supertpv-print-server
#base: core18 # the base snap is the execution environment for this snap
version: '1.2'
summary: Print Server for SuperTPV
description: |
  Print Server for SuperTPV

grade: stable
confinement: strict

apps:
  supertpv-print-server:
    command: wrappers/supertpv-print-server
    plugs: [network, network-bind, raw-usb]


parts:
  supertpv-print-server:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [zlib1g, zlib1g-dev, libjpeg-dev]
    # build-packages: [libexpat1-dev, libpython3-dev, libpython3.5, libpython3.5-dev, python-pip-whl, python3-dev, python3-pip, python3.5-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/

  wrappers:
    plugin: dump
    source: snap_wrap/
