name: supertpv-print-server
#base: core18 # the base snap is the execution environment for this snap
version: '1.3'
summary: Print Server for SuperTPV
description: |
  Print Server for SuperTPV

grade: stable
confinement: strict
architectures: [amd64]

apps:
  server:
    command: wrappers/run
    daemon: simple
    plugs: [network, network-bind, raw-usb, cups-control, process-control]

parts:
  supertpv-print-server:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [zlib1g, zlib1g-dev, libjpeg-dev, cups-bsd]
    build-packages: [libexpat1-dev, libpython3-dev, libpython3.5, libpython3.5-dev, python-pip-whl, python3-dev, python3-pip, python3.5-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/app/

  wrappers:
    plugin: dump
    source: snap_wrap/
