name: supertpv-print-server
version: '1.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Print Server for SuperTPV # 79 char long summary
description: |
  Print Server for SuperTPV

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

#architectures: [amd64, i386]

apps:
  supertpv-print-server:
    command: wrappers/supertpv-print-server
    daemon: simple
    plugs: [network, network-bind, raw-usb]

parts:
  supertpv-print-server:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [zlib1g, zlib1g-dev, libjpeg-dev]
    build-packages: [lxd, libexpat1-dev, libpython3-dev, libpython3.5, libpython3.5-dev, python-pip-whl, python3-dev, python3-pip, python3.5-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/

  wrappers:
    plugin: dump
    source: snap_wrap/
