name: supertpv-print-server
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
summary: Print Server for SuperTPV # 79 char long summary
description: |
  Print Server for SuperTPV

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

#architectures: [amd64, i386]

apps:
  supertpv-print-server:
    command: wrappers/supertpv-print-server
    daemon: simple
    plugs: [network, network-bind]

parts:
  supertpv-print-server:
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [zlib1g, zlib1g-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/

  wrappers:
    plugin: dump
    source: snap_wrap/