name: supertpv-print-server
base: core20
version: '1.7.8'
summary: Print Server for SuperTPV
description: |
  Print Server for SuperTPV

grade: stable
confinement: strict
architectures: [amd64]

apps:
  supertpv-print-server:
    command: wrappers/run
    daemon: simple
    plugs: [network, network-bind, raw-usb, cups-control, process-control]
    environment:
      PYTHONPATH: $SNAP/lib/python3/dist-packages

parts:
  supertpv-print-server:
    plugin: python
    source: .
    requirements: [requirements.txt]
    stage:
      - -app/env/.Python
      - -app/env/bin/python
      - -app/env/bin/python3
      - -app/env/bin/python3.9
    stage-packages:
      - libpython3.9-stdlib
      - libpython3.9-minimal
      - python3.9-minimal
      - zlib1g
      - zlib1g-dev
      - libjpeg-dev
      - cups-bsd
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/lib/python3/dist-packages:$PYTHONPATH
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/app/

  wrappers:
    plugin: dump
    source: snap_wrap/
