name: supertpv-print-server
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Print Server for SuperTPV # 79 char long summary
description: |
  Print Server for SuperTPV

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  supertpv-print-server:
    #environment:
      #FLASK_SECRETS: $SNAP_COMMON/flask_secrets.py
    command: bin/run
    daemon: simple
  # nginx-wrap:
  #   command: wrappers/nginx-wrap
  #   daemon: simple

parts:
  supertpv-print-server:
#    after: [nginx-wrap]
    plugin: python
    source: .
    python-version: python3
    requirements: requirements.txt
    stage-packages: [libpq-dev,libssl-dev]
    install: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/flask-app
      cp -r ./* $SNAPCRAFT_PART_INSTALL/flask-app/
  bin:
    plugin: dump
    source: bin/
  # nginx-wrap:
  #   plugin: nginx
  #   source: .
  #   install: |
  #     rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf.default
  #     rm $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf
  #     cp ./nginx.conf.snap.template $SNAPCRAFT_PART_INSTALL/nginx/conf/nginx.conf