name: Deploy Edge to Snapcraft

on:
  push:
    branches:
      - main
      - master

env:
  CI: false

jobs:
  publish-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: build

      - name: Publish to Edge
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_TOKEN }}
        with:
          store_login: ${{ secrets.SNAPSTORE_TOKEN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
