name: Deploy Edge to Snapcraft

on:
  push:
    branches:
      - main
      - master

env:
  CI: false

jobs:
  publish-edge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snapcraft
        run: sudo snap install snapcraft --classic

      - name: Build and Publish to Edge
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPSTORE_TOKEN }}
        run: ./build
